services:
  postgresDB:
    image: postgres:15-bullseye
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=<your-username>
      - POSTGRES_PASSWORD=<your-password>
      - POSTGRES_DB=course-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  pdAdmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin4
    restart: always
    depends_on:
      - postgresDB
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=<your-email>
      - PGADMIN_DEFAULT_PASSWORD=<your-password>
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json